# calling child module → uses: <owner>/<repo>/.github/workflows/<workflow-file>@<ref>
  # joindevops-actions → GitHub org/user
  # your-repo → repository where workflow lives
  # .github/workflows/common-ci-cd.yml → workflow file
  # @main → branch or tag reference

# deploy_repo: <owner>/<repository>

name: catalogue pipeline

on:
  push:
    # GitHub can trigger workflows on any branch by default, but often you only want certain branches to start a workflow.
    branches: 
      - dev
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: dev

jobs:
  deploy:
    uses: mlnawsdevops/reusable-workflows/.github/workflows/common-ci.yml@main

    with:
      project: roboshop
      component: catalogue
      app_type: nodejs
      aws_account_id: "160885265516"

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}